2017-06-07T09:51:20+0000 [HoneyPotSSHTransport,8835,5.188.10.249] Remote SSH version: SSH-2.0-libssh2_1.7.0
2017-06-07T09:51:20+0000 [HoneyPotSSHTransport,8835,5.188.10.249] kex alg, key alg: 'diffie-hellman-group-exchange-sha256' 'ssh-rsa'
2017-06-07T09:51:20+0000 [HoneyPotSSHTransport,8835,5.188.10.249] outgoing: 'aes256-cbc' 'hmac-sha1' 'none'
2017-06-07T09:51:20+0000 [HoneyPotSSHTransport,8835,5.188.10.249] incoming: 'aes256-cbc' 'hmac-sha1' 'none'
2017-06-07T09:51:21+0000 [HoneyPotSSHTransport,8835,5.188.10.249] NEW KEYS
2017-06-07T09:51:21+0000 [HoneyPotSSHTransport,8835,5.188.10.249] starting service 'ssh-userauth'
2017-06-07T09:51:21+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,8835,5.188.10.249] 'admin' trying auth 'none'
2017-06-07T09:51:22+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,8835,5.188.10.249] 'admin' authenticated with 'none'
2017-06-07T09:51:22+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,8835,5.188.10.249] starting service 'ssh-connection'
2017-06-07T09:51:22+0000 [SSHService 'ssh-connection' on HoneyPotSSHTransport,8737,91.195.103.181] got channel 'direct-tcpip' request
2017-06-07T09:51:22+0000 [SSHService 'ssh-connection' on HoneyPotSSHTransport,8737,91.195.103.181] direct-tcp connection request to 104.81.240.34:443 from localhost:5556
2017-06-07T09:51:22+0000 [SSHService 'ssh-connection' on HoneyPotSSHTransport,8835,5.188.10.249] got channel 'direct-tcpip' request
2017-06-07T09:51:22+0000 [SSHService 'ssh-connection' on HoneyPotSSHTransport,8835,5.188.10.249] direct-tcp connection request to speedtest.tele2.net:80 from 127.0.0.1:8082
2017-06-07T09:51:22+0000 [SSHChannel None (0) on SSHService 'ssh-connection' on HoneyPotSSHTransport,8835,5.188.10.249] remote eof
2017-06-07T09:51:23+0000 [SSHChannel None (0) on SSHService 'ssh-connection' on HoneyPotSSHTransport,8835,5.188.10.249] remote close
2017-06-07T09:51:23+0000 [SSHChannel None (0) on SSHService 'ssh-connection' on HoneyPotSSHTransport,8835,5.188.10.249] sending close 0
2017-06-07T09:51:23+0000 [SSHChannel None (68) on SSHService 'ssh-connection' on HoneyPotSSHTransport,8737,91.195.103.181] direct-tcp forward to 104.81.240.34:443 with data "\x16\x03\x03\x00\xb5\x01\x00\x00\xb1\x03\x03Y7\xccjN\xf0\xa4\xe7\xfe\x86\x10\xfd\xd1\x9aM\xb9o9'\x95\x16\xbaVo\xf9\xbf\x86\x0c\xa6\x14Yy\x00\x00.\xc0,\xc0+\xc00\xc0/\x00\x9f\x00\x9e\xc0$\xc0#\xc0(\xc0'\xc0\n\xc0\t\xc0\x14\xc0\x13\x00\x9d\x00\x9c\x00=\x00<\x005\x00/\x00\n\x00\x05\x00\x04\x01\x00\x00Z\x00\x00\x00\x1f\x00\x1d\x00\x00\x1aauth.np.ac.playstation.net\x00\n\x00\x08\x00\x06\x00\x1d\x00\x17\x00\x18\x00\x0b\x00\x02\x01\x00\x00\r\x00\x14\x00\x12\x04\x01\x05\x01\x02\x01\x04\x03\x05\x03\x02\x03\x02\x02\x06\x01\x06\x03\x00#\x00\x00\x00\x17\x00\x00\xff\x01\x00\x01\x00"
2017-06-07T09:51:23+0000 [SSHChannel None (68) on SSHService 'ssh-connection' on HoneyPotSSHTransport,8737,91.195.103.181] failed to connect: Connection refused
2017-06-07T09:51:23+0000 [SSHChannel None (68) on SSHService 'ssh-connection' on HoneyPotSSHTransport,8737,91.195.103.181] sending close 68
2017-06-07T09:51:23+0000 [SSHService 'ssh-connection' on HoneyPotSSHTransport,8835,5.188.10.249] got channel 'direct-tcpip' request
2017-06-07T09:51:23+0000 [SSHService 'ssh-connection' on HoneyPotSSHTransport,8835,5.188.10.249] direct-tcp connection request to ip-score.com:80 from 127.0.0.1:8082
2017-06-07T09:51:23+0000 [SSHChannel None (1) on SSHService 'ssh-connection' on HoneyPotSSHTransport,8835,5.188.10.249] direct-tcp forward to ip-score.com:80 with data 'GET /? HTTP/1.0\r\n\r\n'
2017-06-07T09:51:23+0000 [SSHChannel None (1) on SSHService 'ssh-connection' on HoneyPotSSHTransport,8835,5.188.10.249] failed to connect: Connection refused
2017-06-07T09:51:23+0000 [SSHChannel None (1) on SSHService 'ssh-connection' on HoneyPotSSHTransport,8835,5.188.10.249] sending close 1
2017-06-07T09:51:23+0000 [HoneyPotSSHTransport,8835,5.188.10.249] Got remote error, code 11
	reason: Client disconnecting normally
2017-06-07T09:51:23+0000 [SSHChannel None (1) on SSHService 'ssh-connection' on HoneyPotSSHTransport,8835,5.188.10.249] remote eof
2017-06-07T09:51:23+0000 [SSHChannel None (1) on SSHService 'ssh-connection' on HoneyPotSSHTransport,8835,5.188.10.249] remote close
2017-06-07T09:51:23+0000 [HoneyPotSSHTransport,8835,5.188.10.249] avatar admin logging out
2017-06-07T09:51:23+0000 [HoneyPotSSHTransport,8835,5.188.10.249] connection lost
2017-06-07T09:51:23+0000 [HoneyPotSSHTransport,8835,5.188.10.249] Connection lost after 2 seconds
2017-06-07T09:51:35+0000 [cowrie.telnet.transport.HoneyPotTelnetFactory] New connection: 94.25.176.91:24611 (10.8.41.81:2223) [session: TT23652]
2017-06-07T09:51:35+0000 [CowrieTelnetTransport,23652,94.25.176.91] first time for 94.25.176.91, need: 1
2017-06-07T09:51:35+0000 [CowrieTelnetTransport,23652,94.25.176.91] login attempt: 1
2017-06-07T09:51:37+0000 [CowrieTelnetTransport,23652,94.25.176.91] login attempt [GET http://check2.zennolab.com/proxy.php HTTP/1.1/Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8] succeeded
2017-06-07T09:51:39+0000 [CowrieTelnetTransport,23652,94.25.176.91] Opening TTY Log: log/tty/20170607-095139-None-23652i.log
2017-06-07T09:51:39+0000 [CowrieTelnetTransport,23652,94.25.176.91] Warning: state changed and new state returned
2017-06-07T09:51:39+0000 [CowrieTelnetTransport,23652,94.25.176.91] CMD: Connection: Close
2017-06-07T09:51:39+0000 [CowrieTelnetTransport,23652,94.25.176.91] Command not found: Connection: Close
2017-06-07T09:51:39+0000 [CowrieTelnetTransport,23652,94.25.176.91] CMD: User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
2017-06-07T09:51:39+0000 [CowrieTelnetTransport,23652,94.25.176.91] Command not found: User-Agent: Mozilla/5.0 Windows NT 10.0
2017-06-07T09:51:39+0000 [CowrieTelnetTransport,23652,94.25.176.91] Command not found: WOW64
2017-06-07T09:51:39+0000 [CowrieTelnetTransport,23652,94.25.176.91] Command not found: rv:45.0 Gecko/20100101 Firefox/45.0
2017-06-07T09:51:39+0000 [CowrieTelnetTransport,23652,94.25.176.91] CMD: Accept-Language: en-US,en;q=0.5
2017-06-07T09:51:39+0000 [CowrieTelnetTransport,23652,94.25.176.91] Command not found: Accept-Language: en-US , en
2017-06-07T09:51:39+0000 [CowrieTelnetTransport,23652,94.25.176.91] Unhandled Error
	Traceback (most recent call last):
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
	    return self._dataReceived(data)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/conch/telnet.py", line 636, in dataReceived
	    self.applicationDataReceived(b''.join(appDataBuffer))
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/conch/telnet.py", line 988, in applicationDataReceived
	    self.protocol.dataReceived(data)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
	    why = self.lineReceived(line)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/conch/telnet.py", line 1100, in lineReceived
	    newState = getattr(self, "telnet_" + oldState)(line)
	  File "/home/cowrie/cowrie/cowrie/telnet/transport.py", line 142, in telnet_Command
	    self.transport.protocol.dataReceived(command+'\r')
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/conch/telnet.py", line 1035, in dataReceived
	    self.protocol.dataReceived(data)
	  File "/home/cowrie/cowrie/cowrie/insults/insults.py", line 112, in dataReceived
	    insults.ServerProtocol.dataReceived(self, data)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/conch/insults/insults.py", line 537, in dataReceived
	    self.terminalProtocol.keystrokeReceived(ch, None)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/conch/recvline.py", line 225, in keystrokeReceived
	    m()
	  File "/home/cowrie/cowrie/cowrie/core/protocol.py", line 353, in handle_RETURN
	    return recvline.RecvLine.handle_RETURN(self)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/conch/recvline.py", line 292, in handle_RETURN
	    self.lineReceived(line)
	  File "/home/cowrie/cowrie/cowrie/core/protocol.py", line 187, in lineReceived
	    self.cmdstack[-1].lineReceived(line)
	  File "/home/cowrie/cowrie/cowrie/core/honeypot.py", line 246, in lineReceived
	    self.runCommand()
	  File "/home/cowrie/cowrie/cowrie/core/honeypot.py", line 351, in runCommand
	    runOrPrompt()
	  File "/home/cowrie/cowrie/cowrie/core/honeypot.py", line 257, in runOrPrompt
	    self.runCommand()
	  File "/home/cowrie/cowrie/cowrie/core/honeypot.py", line 307, in runCommand
	    if not cmd['command']:
	exceptions.KeyError: 'command'
	
2017-06-07T09:51:39+0000 [CowrieTelnetTransport,23652,94.25.176.91] Closing TTY Log: log/tty/20170607-095139-None-23652i.log after 0 seconds
2017-06-07T09:51:39+0000 [CowrieTelnetTransport,23652,94.25.176.91] honeypot terminal protocol connection lost [Failure instance: Traceback (failure with no frames): <type 'exceptions.KeyError'>: 'command'
	]
2017-06-07T09:51:39+0000 [CowrieTelnetTransport,23652,94.25.176.91] Connection lost after 3 seconds
2017-06-07T09:51:56+0000 [SSHService 'ssh-connection' on HoneyPotSSHTransport,8732,91.195.103.211] got channel 'direct-tcpip' request
2017-06-07T09:51:56+0000 [SSHService 'ssh-connection' on HoneyPotSSHTransport,8732,91.195.103.211] direct-tcp connection request to 66.196.118.35:25 from localhost:5556
2017-06-07T09:52:00+0000 [cowrie.telnet.transport.HoneyPotTelnetFactory] New connection: 37.23.195.187:55767 (10.8.41.81:2223) [session: TT23653]
