2017-06-15T04:31:22+0000 [HoneyPotSSHTransport,32405,113.195.145.52] connection lost
2017-06-15T04:31:23+0000 [HoneyPotSSHTransport,32405,113.195.145.52] Connection lost after 5 seconds
2017-06-15T04:31:27+0000 [cowrie.ssh.factory.CowrieSSHFactory] New connection: 113.195.145.52:29426 (10.8.41.81:2222) [session: da5de099]
2017-06-15T04:31:30+0000 [HoneyPotSSHTransport,32406,113.195.145.52] Remote SSH version: SSH-2.0-PUTTY
2017-06-15T04:31:30+0000 [HoneyPotSSHTransport,32406,113.195.145.52] kex alg, key alg: 'diffie-hellman-group14-sha1' 'ssh-rsa'
2017-06-15T04:31:30+0000 [HoneyPotSSHTransport,32406,113.195.145.52] outgoing: 'aes128-ctr' 'hmac-sha1' 'none'
2017-06-15T04:31:30+0000 [HoneyPotSSHTransport,32406,113.195.145.52] incoming: 'aes128-ctr' 'hmac-sha1' 'none'
2017-06-15T04:31:38+0000 [cowrie.ssh.factory.CowrieSSHFactory] New connection: 115.78.10.86:55574 (10.8.41.81:2222) [session: 51948042]
2017-06-15T04:31:38+0000 [HoneyPotSSHTransport,32407,115.78.10.86] Remote SSH version: SSH-2.0-Granados-1.0
2017-06-15T04:31:38+0000 [HoneyPotSSHTransport,32407,115.78.10.86] kex alg, key alg: 'diffie-hellman-group1-sha1' 'ssh-dss'
2017-06-15T04:31:38+0000 [HoneyPotSSHTransport,32407,115.78.10.86] outgoing: 'aes128-cbc' 'hmac-sha1' 'none'
2017-06-15T04:31:38+0000 [HoneyPotSSHTransport,32407,115.78.10.86] incoming: 'aes128-cbc' 'hmac-sha1' 'none'
2017-06-15T04:31:39+0000 [HoneyPotSSHTransport,32407,115.78.10.86] NEW KEYS
2017-06-15T04:31:39+0000 [HoneyPotSSHTransport,32406,113.195.145.52] connection lost
2017-06-15T04:31:39+0000 [HoneyPotSSHTransport,32406,113.195.145.52] Connection lost after 11 seconds
2017-06-15T04:31:39+0000 [HoneyPotSSHTransport,32407,115.78.10.86] starting service 'ssh-userauth'
2017-06-15T04:31:40+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,32407,115.78.10.86] 'user' trying auth 'password'
2017-06-15T04:31:41+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,32407,115.78.10.86] login attempt: 12
2017-06-15T04:31:41+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,32407,115.78.10.86] login return, expect: [support/support]
2017-06-15T04:31:44+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,32407,115.78.10.86] login attempt [user/1234] failed
2017-06-15T04:31:45+0000 [-] 'user' failed auth 'password'
2017-06-15T04:31:45+0000 [-] unauthorized login: 
2017-06-15T04:31:46+0000 [HoneyPotSSHTransport,32407,115.78.10.86] connection lost
2017-06-15T04:31:46+0000 [HoneyPotSSHTransport,32407,115.78.10.86] Connection lost after 8 seconds
2017-06-15T04:31:54+0000 [CowrieTelnetTransport,56114,216.120.247.147] Closing TTY Log: log/tty/20170615-042952-None-56114i.log after 122 seconds
2017-06-15T04:31:54+0000 [CowrieTelnetTransport,56114,216.120.247.147] honeypot terminal protocol connection lost [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
	]
2017-06-15T04:31:54+0000 [CowrieTelnetTransport,56114,216.120.247.147] Connection lost after 131 seconds
2017-06-15T04:31:58+0000 [cowrie.ssh.factory.CowrieSSHFactory] New connection: 113.195.145.52:17117 (10.8.41.81:2222) [session: 23e4a991]
2017-06-15T04:31:59+0000 [HoneyPotSSHTransport,32408,113.195.145.52] Remote SSH version: SSH-2.0-PUTTY
2017-06-15T04:31:59+0000 [HoneyPotSSHTransport,32408,113.195.145.52] kex alg, key alg: 'diffie-hellman-group14-sha1' 'ssh-rsa'
2017-06-15T04:31:59+0000 [HoneyPotSSHTransport,32408,113.195.145.52] outgoing: 'aes128-ctr' 'hmac-sha1' 'none'
2017-06-15T04:31:59+0000 [HoneyPotSSHTransport,32408,113.195.145.52] incoming: 'aes128-ctr' 'hmac-sha1' 'none'
2017-06-15T04:32:01+0000 [cowrie.ssh.factory.CowrieSSHFactory] New connection: 113.195.145.52:45241 (10.8.41.81:2222) [session: 77e2eb67]
2017-06-15T04:32:04+0000 [HoneyPotSSHTransport,32408,113.195.145.52] connection lost
2017-06-15T04:32:04+0000 [HoneyPotSSHTransport,32408,113.195.145.52] Connection lost after 5 seconds
2017-06-15T04:32:04+0000 [HoneyPotSSHTransport,32409,113.195.145.52] Remote SSH version: SSH-2.0-PUTTY
2017-06-15T04:32:04+0000 [HoneyPotSSHTransport,32409,113.195.145.52] kex alg, key alg: 'diffie-hellman-group14-sha1' 'ssh-rsa'
2017-06-15T04:32:04+0000 [HoneyPotSSHTransport,32409,113.195.145.52] outgoing: 'aes128-ctr' 'hmac-sha1' 'none'
2017-06-15T04:32:04+0000 [HoneyPotSSHTransport,32409,113.195.145.52] incoming: 'aes128-ctr' 'hmac-sha1' 'none'
2017-06-15T04:32:06+0000 [HoneyPotSSHTransport,32409,113.195.145.52] NEW KEYS
2017-06-15T04:32:07+0000 [HoneyPotSSHTransport,32409,113.195.145.52] starting service 'ssh-userauth'
2017-06-15T04:32:10+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,32409,113.195.145.52] 'root' trying auth 'none'
2017-06-15T04:32:12+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,32409,113.195.145.52] 'root' authenticated with 'none'
2017-06-15T04:32:12+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,32409,113.195.145.52] starting service 'ssh-connection'
2017-06-15T04:32:12+0000 [HoneyPotSSHTransport,32409,113.195.145.52] Got remote error, code 11
	reason: 
2017-06-15T04:32:12+0000 [HoneyPotSSHTransport,32409,113.195.145.52] avatar root logging out
2017-06-15T04:32:12+0000 [HoneyPotSSHTransport,32409,113.195.145.52] connection lost
2017-06-15T04:32:12+0000 [HoneyPotSSHTransport,32409,113.195.145.52] Connection lost after 10 seconds
2017-06-15T04:32:19+0000 [cowrie.ssh.factory.CowrieSSHFactory] New connection: 113.195.145.52:43540 (10.8.41.81:2222) [session: fef4b4a8]
2017-06-15T04:32:22+0000 [HoneyPotSSHTransport,32410,113.195.145.52] Remote SSH version: SSH-2.0-PUTTY
2017-06-15T04:32:22+0000 [HoneyPotSSHTransport,32410,113.195.145.52] kex alg, key alg: 'diffie-hellman-group14-sha1' 'ssh-rsa'
2017-06-15T04:32:22+0000 [HoneyPotSSHTransport,32410,113.195.145.52] outgoing: 'aes128-ctr' 'hmac-sha1' 'none'
2017-06-15T04:32:22+0000 [HoneyPotSSHTransport,32410,113.195.145.52] incoming: 'aes128-ctr' 'hmac-sha1' 'none'
2017-06-15T04:32:23+0000 [HoneyPotSSHTransport,32410,113.195.145.52] NEW KEYS
2017-06-15T04:32:24+0000 [HoneyPotSSHTransport,32410,113.195.145.52] starting service 'ssh-userauth'
2017-06-15T04:32:28+0000 [HoneyPotSSHTransport,32410,113.195.145.52] Got remote error, code 11
	reason: 
2017-06-15T04:32:28+0000 [HoneyPotSSHTransport,32410,113.195.145.52] connection lost
2017-06-15T04:32:28+0000 [HoneyPotSSHTransport,32410,113.195.145.52] Connection lost after 8 seconds
2017-06-15T04:32:31+0000 [cowrie.telnet.transport.HoneyPotTelnetFactory] New connection: 163.172.199.104:20047 (10.8.41.81:2223) [session: TT56115]
2017-06-15T04:32:31+0000 [CowrieTelnetTransport,56115,163.172.199.104] first time for 163.172.199.104, need: 1
2017-06-15T04:32:31+0000 [CowrieTelnetTransport,56115,163.172.199.104] login attempt: 1
2017-06-15T04:32:34+0000 [CowrieTelnetTransport,56115,163.172.199.104] login attempt [CONNECT pgorelease.nianticlabs.com:443 HTTP/1.1/TE: deflate,gzip;q=0.3] succeeded
2017-06-15T04:32:35+0000 [CowrieTelnetTransport,56115,163.172.199.104] Opening TTY Log: log/tty/20170615-043235-None-56115i.log
2017-06-15T04:32:35+0000 [CowrieTelnetTransport,56115,163.172.199.104] Warning: state changed and new state returned
2017-06-15T04:32:35+0000 [CowrieTelnetTransport,56115,163.172.199.104] CMD: Connection: TE, close
2017-06-15T04:32:35+0000 [CowrieTelnetTransport,56115,163.172.199.104] Command not found: Connection: TE , close
2017-06-15T04:32:35+0000 [CowrieTelnetTransport,56115,163.172.199.104] CMD: Host: pgorelease.nianticlabs.com:443
2017-06-15T04:32:35+0000 [CowrieTelnetTransport,56115,163.172.199.104] Command not found: Host: pgorelease.nianticlabs.com:443
2017-06-15T04:32:35+0000 [CowrieTelnetTransport,56115,163.172.199.104] CMD: 
2017-06-15T04:32:35+0000 [CowrieTelnetTransport,56115,163.172.199.104] Unhandled Error
	Traceback (most recent call last):
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
	    return self._dataReceived(data)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/conch/telnet.py", line 585, in dataReceived
	    raise ValueError("Stumped", b)
	exceptions.ValueError: ('Stumped', '\x01')
	
2017-06-15T04:32:35+0000 [CowrieTelnetTransport,56115,163.172.199.104] Closing TTY Log: log/tty/20170615-043235-None-56115i.log after 0 seconds
2017-06-15T04:32:35+0000 [CowrieTelnetTransport,56115,163.172.199.104] honeypot terminal protocol connection lost [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: ('Stumped', '\x01')
	]
2017-06-15T04:32:35+0000 [CowrieTelnetTransport,56115,163.172.199.104] Connection lost after 4 seconds
2017-06-15T04:32:42+0000 [cowrie.ssh.factory.CowrieSSHFactory] New connection: 113.195.145.52:12946 (10.8.41.81:2222) [session: c2c87497]
2017-06-15T04:32:43+0000 [HoneyPotSSHTransport,32411,113.195.145.52] Remote SSH version: SSH-2.0-PUTTY
2017-06-15T04:32:43+0000 [HoneyPotSSHTransport,32411,113.195.145.52] kex alg, key alg: 'diffie-hellman-group14-sha1' 'ssh-rsa'
2017-06-15T04:32:43+0000 [HoneyPotSSHTransport,32411,113.195.145.52] outgoing: 'aes128-ctr' 'hmac-sha1' 'none'
2017-06-15T04:32:43+0000 [HoneyPotSSHTransport,32411,113.195.145.52] incoming: 'aes128-ctr' 'hmac-sha1' 'none'
2017-06-15T04:32:45+0000 [HoneyPotSSHTransport,32411,113.195.145.52] NEW KEYS
2017-06-15T04:32:46+0000 [HoneyPotSSHTransport,32411,113.195.145.52] starting service 'ssh-userauth'
2017-06-15T04:32:46+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,32411,113.195.145.52] 'root' trying auth 'none'
2017-06-15T04:32:48+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,32411,113.195.145.52] 'root' authenticated with 'none'
2017-06-15T04:32:48+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,32411,113.195.145.52] starting service 'ssh-connection'
2017-06-15T04:32:48+0000 [HoneyPotSSHTransport,32411,113.195.145.52] Got remote error, code 11
	reason: 
2017-06-15T04:32:48+0000 [HoneyPotSSHTransport,32411,113.195.145.52] avatar root logging out
2017-06-15T04:32:48+0000 [HoneyPotSSHTransport,32411,113.195.145.52] connection lost
2017-06-15T04:32:48+0000 [HoneyPotSSHTransport,32411,113.195.145.52] Connection lost after 5 seconds
2017-06-15T04:33:00+0000 [cowrie.ssh.factory.CowrieSSHFactory] New connection: 185.145.252.26:15069 (10.8.41.81:2222) [session: 90f50cf4]
2017-06-15T04:33:00+0000 [HoneyPotSSHTransport,32412,185.145.252.26] Remote SSH version: SSH-2.0-JSCH_0.1.51
2017-06-15T04:33:00+0000 [HoneyPotSSHTransport,32412,185.145.252.26] kex alg, key alg: 'diffie-hellman-group-exchange-sha256' 'ssh-rsa'
2017-06-15T04:33:00+0000 [HoneyPotSSHTransport,32412,185.145.252.26] outgoing: 'aes128-ctr' 'hmac-sha1' 'none'
2017-06-15T04:33:00+0000 [HoneyPotSSHTransport,32412,185.145.252.26] incoming: 'aes128-ctr' 'hmac-sha1' 'none'
2017-06-15T04:33:00+0000 [HoneyPotSSHTransport,32412,185.145.252.26] NEW KEYS
2017-06-15T04:33:00+0000 [HoneyPotSSHTransport,32412,185.145.252.26] starting service 'ssh-userauth'
2017-06-15T04:33:00+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,32412,185.145.252.26] 'administrator' trying auth 'none'
